// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSa5ncngKgXcI4s-ZeX8Ctipx3Z5c2eWw',
    appId: '1:1032299672180:web:cd22ea6c410ea939149721',
    messagingSenderId: '1032299672180',
    projectId: 'resturant-9e9ef',
    authDomain: 'resturant-9e9ef.firebaseapp.com',
    storageBucket: 'resturant-9e9ef.appspot.com',
    measurementId: 'G-4L9HEXQ2D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChyNZv77Yo4W2fTNFvnmROGl-IzYoKPhU',
    appId: '1:1032299672180:android:1d8e908638425c0a149721',
    messagingSenderId: '1032299672180',
    projectId: 'resturant-9e9ef',
    storageBucket: 'resturant-9e9ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg-yEqdifAm6GgOJGQ6K7xin47TdrRFjA',
    appId: '1:1032299672180:ios:ce999e0693763514149721',
    messagingSenderId: '1032299672180',
    projectId: 'resturant-9e9ef',
    storageBucket: 'resturant-9e9ef.appspot.com',
    iosClientId: '1032299672180-r0i3n9su4koqmv84tlc4i121q1fhc43n.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminCalebg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg-yEqdifAm6GgOJGQ6K7xin47TdrRFjA',
    appId: '1:1032299672180:ios:d6cfca3df9846168149721',
    messagingSenderId: '1032299672180',
    projectId: 'resturant-9e9ef',
    storageBucket: 'resturant-9e9ef.appspot.com',
    iosClientId: '1032299672180-9cfjigu2lj5nvhe1918s0geodja0on5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminCalebg.RunnerTests',
  );
}
